name: ukalender
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_localization: ^0.2.2
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  time_picker_with_timezone: ^0.0.6
  mailer: ^6.2.0
  sqflite: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.5
  icons_launcher: ^3.0.0
  uuid: ^4.5.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - assets/icon/play_store_512.png
